### PR TITLE
bzip2 is a dependency for installing patternfly, phantomjs

### PR DESCRIPTION
**Pull request by ryanj**
see https://github.com/ryanj/origin-s2i-nodejs/issues/8

### CODE REVIEW

**Comment by ryanj** [comment]
Let me know if you'd rather have this added to sti-base.  other language-specific build tooling might need it as well...

**Comment by ryanj** [comment]
The [patternfly](https://www.patternfly.org/) team needs this as well

**Comment by bparees** [comment]
let's leave it here for now, we can always push it down later.

**Comment by ryanj** [comment]
thanks!

**Comment by elyscape** [comment]
@ryanj: Be advised that PhantomJS also needs `freetype` and `fontconfig` in order to run correctly.

**Comment by elyscape** [comment]
Also, this should update `Dockerfile.rhel7` as well.

**Comment by ryanj** [comment]
@elyscape good catch, I'll send an update for `Dockerfile.rhel7`.

It looks like `freetype` and `fontconfig` are available in the centos base image.  

Are they not included in the rhel base image?  Do they need to be added to the rhel Dockerfile as well?

**Comment by elyscape** [comment]
> It looks like `freetype` and `fontconfig` are available in the centos base image.

Interesting. That must have changed, as I definitely had to install them for some of the work I've been doing.

> Are they not included in the rhel base image? Do they need to be added to the rhel Dockerfile as well?

I don't have access to this image, so I couldn't say.

**Comment by bparees** [comment]
@ryanj i already caught the rhel7 miss and included it in my nss pr:
https://github.com/openshift/s2i-nodejs/pull/95/files#diff-debeaecb79f21738a847dd9c4a710bf7R32

**Pull request merged**
