### PR TITLE
move debug settings into run script

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@Ian-Stewart-Binks @mfojtik i feel like this belongs here instead of in the scl_enable script.

@Ian-Stewart-Binks was there a reason you put it in scl_enable instead?  scl_enable will contain stuff that gets run when a user exec's into a running container.

**Comment by bparees** [comment]
@ryanj fyi

**Comment by Ian-Stewart-Binks** [comment]
@bparees It had something to do with the setting of the environment variables. I recall [this](http://stackoverflow.com/questions/10781824/export-not-working-in-my-shell-script) being relevant.

**Comment by mfojtik** [comment]
@bparees no idea why we have that in SCL enable script, good catch!

**Comment by mfojtik** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@ryanj @mfojtik i've updated this to fix the env variable testing logic and also print the variable values out when the application starts.  ptal.

users who exec into a running container will not see the same env variables that the node process is running with, since the variables are set by the "run" script based on the value of DEV_MODE, but that doesn't seem like a huge problem to me.

**Comment by bparees** [comment]
@ryanj @mfojtik bump

**Comment by mfojtik** [comment]
LGTM

**Pull request merged**
